sonar.projectKey=hugo-tasklist-frontend-exam
sonar.projectName=hugo-tasklist-frontend-exam
sonar.sources=src
sonar.tests=src/__tests__
sonar.sources.exclusions=src/__tests__/**
sonar.exclusions=node_modules/**,dist/**,coverage/**,reports/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
