sonar.projectKey=cicd-tasklist-frontend
sonar.projectName=cicd-tasklist-frontend
sonar.sources=src
sonar.tests=src/__tests__
sonar.exclusions=node_modules/**,dist/**,coverage/**,reports/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
